### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by budikesuma** [zerty/Wuxiaworld-to-epub#1]
@zerty 
Hello,
How to install this package in terminal?
Any commands?

**Comment by gammesB** [comment]
you need python. and then
you can do "pip install -r requirements.txt" like all other python projects.
then what I did as I was lazy was just changing the bottom of main.py to the project i wanted.
and then did "Python Main.py" in the terminal
the default was xhtml files which for my use is okay.

It doesn't have a ui or anything so not a good start for someone who never programs/never uses a terminal altough i hope my steps help, as the description states it's more a example.

**Comment by zerty** [comment]
Thanks for answering @gammesB , I've updated the README. If I get some time, T'll make some kind of interface but the current system will only work until November 21st, 2022 ...

**Comment by budikesuma** [comment]
@zerty 

It's a good idea to make it a python package that can be directly installed via zip/git (your package doesn't have a `setup.py` file yet).

For example with the command:

`pip install Wuxiaworld-to-epub-main.zip` (if downloaded to local).

Or via git:

`pip install git+https://github.com/zerty/Wuxiaworld-to-epub.git`

This will make it easier for novice users like us...
